export const ACTION_TYPE = {
  INITIAL_DATA: "INITIAL_DATA",
  BRAND_FILTER: "BRAND_FILTER",
  GENDER_FILTER: " GENDER_FILTER",
  SIZE_FILTER: "SIZE_FILTER",
  SORT_BY: "SORT_BY",
  LOW_TO_HIGH: "LOW_TO_HIGH",
  HIGH_TO_LOW: "HIGH_TO_LOW",
  CLEAR_ALL: "CLEAR_ALL",
};
